#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryuya Nakamura
# SPDX-License-Identifier: BSD-3-Clause
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans1 = 0
ans2 = 0
ans3 = 1
ans4 = 1.0

for line in sys.stdin:
    line = line.rstrip()
    ans1 += tonum(line)
    ans2 -= tonum(line)
    ans3 *= tonum(line)
    ans4 /= tonum(line)

print(int(ans1), int(ans2), int(ans3), float(ans4))
