#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryuya Nakamura
# SPDX-License-Identifier: BSD-3-Clause
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans1 = 0
ans2 = 0


for line in sys.stdin:
    line = line.rstrip()
    ans1 += tonum(line)
    ans2 -= tonum(line)


print(int(ans1))
print(int(ans2))
